config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'guia-de-la-ley', to: 'pages#the_law', as: :the_law
  get 'glosario', to: 'pages#glossary', as: :glossary
  get 'metodologia', to: 'pages#methodology', as: :methodology

  get 'galeria', to: 'pages#gallery', as: :gallery

  get 'busqueda', to: 'pages#search', as: :search

  resources :public_bodies, path: 'administraciones', only: [:index, :show]

  resources :bidders, path: 'grupos-constructores', only: [:index, :show]

  resources :awards, path: 'contratos', only: [:index, :show]

  resources :articles, path: 'articulos', only: [:index, :show]

  get 'data/grupos-constructores',      to: 'data#grupos_constructores', as: :grupos_constructores
  get 'data/administraciones',          to: 'data#administraciones', as: :data_administraciones

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/views/partials/_admin_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '<h1>Quién Cobra la Obra</h1>', '/', :class => 'navbar-brand' %>
    </div>
  </div>
</nav>

app/views/partials/_contract_awards_table.html.erb
<div class="table-responsive">
  <table id="contracts<% if defined? utes %>-utes<% end %>" class="table table-contracts sortable-theme-minimal" <% if controller_name != 'awards' or (controller_name == 'awards' && !@pagination) %>data-sortable<% end %>>
    <thead>
      <tr>
        <th data-sortable="false"></th>
        <th data-sortable="false">Fuente</th>

        <% if controller_name != 'public_bodies' %>
        <th>Administración pública</th>
        <% end %>

        <% if controller_name != 'bidders' %>
        <th>Grupo constructor</th>
        <% end %>

        <% if controller_name == 'public_bodies' or controller_name == 'bidders' %>
        <th data-sortable="false">Objeto</th>
        <% end %>

        <th>Fecha adjudicación</th>
        <th>Procedimiento</th>

        <th class="text-right" data-sortable-type="numeric" data-sorted="true" data-sorted-direction="descending">Importe <i>(€)</i></th>
      </tr>
    </thead>
    <tbody>
    <% awards.each do |award| %>
      <tr data-id="<%= award.id %>"<% if controller_name != 'public_bodies' %> data-body-type="<%= award.public_body.body_type %>"<% end %>>
        <td><%= link_to '<i class="glyphicon glyphicon-plus"></i>'.html_safe, award_path(award), title: 'Ver más', class: 'read-more' %></td>
        <td class="text-center"><%= link_to '<i class="glyphicon glyphicon-file"></i>'.html_safe, "http://www.boe.es/buscar/doc.php?id=#{award.boe_id}", target: '_blank' %></td>

        <% if controller_name != 'public_bodies' %>
        <td class="td-entity" data-id="<%= award.public_body.id %>"><%= link_to award.public_body.name, public_body_path(award.public_body) unless award.public_body.name.blank? %></td>
        <% end %>

        <% if controller_name != 'bidders' %>
        <td class="td-entity" data-id="<%= award.bidder.slug %>">
          <%= render_bidder_group(award) %>
        </td>
        <% end %>

        <% if controller_name == 'public_bodies' or controller_name == 'bidders' %>
        <td class="td-description"><%= truncate(award.description, length: 112) %></td>
        <% end %>

        <td class="td-date" data-value="<%= award.award_date %>"><%= award.award_date.strftime('%d-%m-%Y') %></td>
        <% if award.process_type.blank? %>
        <td>-</td>
        <% else %>
        <td><%= award.process_type %></td>
        <% end %>

        <td class="td-amount text-right" data-value="<%= award.amount.to_f*0.01 %>"><strong><%= number_with_precision(award.amount.to_f*0.01, precision: 0, delimiter: ".") %></strong></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/partials/_entities.html.erb
<div class="entities wall row">
 
  <div class="wall-item col-sm-12">
    <div class="panel panel-default">

    <!-- Entities list -->
    <% entities.each do |entity| %>
      <div class="panel-heading">
        <h3><%= link_to entity[field], "#{path}/#{entity.slug}" %></h3>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/partials/_entity.html.erb
<div class="entity-content <%= controller_name %>">

  <div class="title entity single">
    <h2><%= @title %></h2>
  </div>

  <div class="sharing-right">
    <%= render 'partials/sharing_buttons', title: @title %>
  </div>

  <div class="entity-description">
    <% if controller.controller_name == 'bidders' %>
      <p>De todas las adjudicaciones publicadas en el BOE entre <%= year_min() %> y <%= year_max() %>, <strong><%= @title %> <% if @contract_awards.empty? %>no se ha llevado de forma directa ningún contrato<% else %>se ha llevado de forma directa <%= pluralize(@contract_awards.count, 'contrato', 'contratos')%> por un importe de <%= number_to_currency(@contract_awards_amount.to_f*0.01, precision: 0, delimiter: ".") %>.<% end %></strong><% unless @contract_awards_utes.empty? %><% if @contract_awards.empty? %>, pero<% else %> Además,<% end %> ha formado parte de <% if @contract_awards_utes.count>1 %>varias UTE que resultaron adjudicatarias<% else %>una UTE que resultó adjudicataria<% end %> de <% unless @contract_awards.empty? %>otros<% end %> <% if @contract_awards_utes.count>1 %><%= @contract_awards_utes.count %> contratos y que suman<% else %>un contrato por<% end %> <% unless @contract_awards.empty? %>otros<% end %> <%= number_to_currency(@contract_awards_utes_amount.to_f*0.01, precision: 0, delimiter: ".") %>.<% end %></p>
      <p><% unless @contract_awards.empty? or @contract_awards_utes.empty? %>Así, <strong><%= @title %> ha estado presente, en total, en la adjudicación de <% if @contract_awards.count>1 %><%= pluralize(@contract_awards.count+@contract_awards_utes.count, 'contrato', 'contratos') %><% else %>un contrato<% end %> y <%= number_to_currency(@contract_awards_total_amount.to_f*0.01, precision: 0, delimiter: ".") %>.</strong>
      <% end %>
      <% unless @close_bid_total==0 %>
      De esa cantidad, un <%= number_with_precision(@close_bid_total/@contract_awards_total_amount*100.0, precision: 1) %>% del importe fue adjudicado vía procedimiento negociado. <%end %>Entre las administraciones que le contratan, la que tiene mayor peso es <strong><%= @biggest_public_body[0].prefix + ' ' + @biggest_public_body[0].name %></strong> (<%= number_with_precision(@biggest_public_body[1]/@contract_awards_total_amount*100.0, precision: 1) %>% del total del importe adjudicado<% unless @contract_awards_utes.empty? %> tanto de forma directa como a través de las UTE en las que participa<% end %>).
      </p>
    <% else %>
      <p>De todas las adjudicaciones publicadas en el BOE entre <%= year_min() %> y <%= year_max() %>, <%= @title_prefix %><strong><%= @title %></strong> ha adjudicado <strong><%= pluralize(@contract_awards.count, 'contrato', 'contratos')%></strong> por un importe de <strong><%= number_to_currency(@contract_awards_amount.to_f*0.01, precision: 0, delimiter: ".") %></strong><% unless @close_bid_total==0 %>, de los cuales un <%= number_with_precision(@close_bid_total/@contract_awards_amount*100.0, precision: 1) %>% ha sido por procedimiento negociado<% end %>.</p>
      <% if @bidder_breakdown.count > 1 %>
      <p>El principal grupo empresarial beneficiado ha sido <strong><%= @biggest_bidder[0] %></strong> (está presente, de forma directa o a través de UTE, en el <%= number_with_precision(@biggest_bidder[1]/@contract_awards_amount*100.0, precision: 1) %>% del total del importe adjudicado).</p>
      <% else %>
      <p>El único grupo empresarial beneficiado ha sido <strong><%= @bidder_breakdown.first[0] %></strong>.</p>
      <% end %>
    <% end %>
  </div>

  <% if @contract_awards.length > 1 %>
  <div class="row entity-charts">
    <div class="col-md-6">
      <div class="entity-chart-title">
        <% if controller.controller_name == 'bidders' %>
        <h3>Reparto de contratos por administración pública</h3>
        <% else %>
        <h3>Reparto de contratos de forma directa</h3>
        <% end %>
        <% if controller.controller_name == 'bidders' && !@contract_awards_utes.empty? %>
        <div class="utes-switch-container">
          <input id="utes-switch" class="utes-switch" type="checkbox" checked data-size="small" data-on-text="Con UTE" data-off-text="En&nbsp;solitario">
        </div>
        <% end %>
      </div>
      <div id="treemap-chart" class="entity-chart">
        <div class='popover top' role='tooltip'>
          <div class='arrow'></div>
          <div class='popover-title'></div>
          <div class='popover-budget'><strong></strong> € <span class="percentage"></span></div>
        </div>
      </div>
      <% if controller.controller_name == 'bidders' %>
      <div class="well">Distribución de los contratos publicados en el BOE entre <%= year_min() %> y <%= year_max() %>. <strong>Con UTE</strong> incluye todos los contratos <a href="/metodologia#que-pasa-con-las-ute">en los que participa</a>. <strong>En solitario</strong>, solo aquellos que se llevó íntegros.</div>
      <% else %>
        <div class="well">Distribución de forma directa (no suma a los grupos las UTE en las que participan) de los contratos publicados en el BOE entre <%= year_min() %> y <%= year_max() %>.</div>
      <% end %>
    </div>
    <div class="col-md-6">
      <div class="entity-chart-title">
        <% if controller.controller_name == 'bidders' %>
        <h3>Evolución temporal de los contratos recibidos</h3>
        <% else %>
        <h3>Evolución temporal de los contratos adjudicados</h3>
        <% end %>
      </div>
      <div id="timeline-bar-chart" class="entity-chart">
        <div class='popover top' role='tooltip'>
          <div class='arrow'></div>
          <div class='popover-title'><i class="glyphicon glyphicon-calendar"></i><span></span></div>
          <div class='popover-budget'><strong></strong> €</div>
          <% if controller.controller_name == 'bidders' %>
          <div class='popover-budget-data popover-budget-ute'><strong></strong>% <small>en&nbsp;UTE</small></div>
          <div class='popover-budget-data popover-budget-alone'><strong></strong>% <small>en&nbsp;solitario</small></div>
          <% end %>
        </div>
      </div>
      <% if controller.controller_name == 'bidders' %>
      <div class="well">Contratos publicados en el BOE, en solitario y a través de <a href="/metodologia#que-pasa-con-las-ute">UTE</a></div>
      <% else %>
        <div class="well">Incluye todos los contratos adjudicados vía BOE.</div>
      <% end %>
    </div>
  </div>
  <% end %>

  <% unless @qm_id.blank? %>
  <div class="panel panel-default entity-qm-embed">
    <iframe src="https://quienmanda.es/entities/<%= @qm_id %>?widget=1&history=" width="100%" height="450px" scrolling="no" marginheight="0" frameborder="0"></iframe>
  </div>
  <% end %>

  <% if @contract_awards.size > 0 %>
  <div>
    <% if controller.controller_name == 'bidders' %>
    <h3>Contratos adjudicados a <%= @title %> en solitario</h3>
    <% else %>
    <h3>Contratos adjudicados por <%= @title %></h3>
    <% end %>
    <div class="panel panel-default">
      <%= render('partials/contract_awards_table', awards: @contract_awards) %>
    </div>
  </div>
  <% end %>

  <% if controller.controller_name == 'bidders' && !@contract_awards_utes.empty? %>
  <div>
    <h3>Contratos adjudicados a las UTE en las que participa <%= @title %></h3>
    <div class="panel panel-default">
      <%= render('partials/contract_awards_table', awards: @contract_awards_utes, utes: true) %>
    </div>
  </div>
  <% end %>

</div>

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="main-footer text-center">
    <p>Un proyecto de</p>
    <a href="http://www.civio.es" class="logo" title="Civio" target="_blank">
      <%= image_tag("logo-civio.png", alt: "Logo Civio") %>
    </a>
    <p>financiado por crowdfunding en</p>
    <a href="https://goteo.org/project/quien-cobra-la-obra" class="logo" title="Goteo" target="_blank">
      <%= image_tag("logo-goteo.png", alt: "Logo Goteo") %>
    </a>
    <p>gracias a</p>
    <a href="/metodologia#agradecimientos" class="logo" title="Goteo" target="_blank">250 cofinanciadores</a>
    <p>
      <a href="http://www.civio.es/2013/10/re-publica-contenidos-de-civio-y-de-nuestros-proyectos/" title="Re-publica">
        <img src="//i.creativecommons.org/l/by-sa/3.0/88x31.png" alt="Creative commons">
      </a>
    </p>
  </div>
  <div class="sub-footer">
    <p class="text-center">© 2016 · Fundación Ciudadana Civio</p>
  </div>
</footer>

app/views/partials/_gallery_preview.html.erb
<!-- Gallery -->
<div class="posts posts-highlighted row">
  <div class="wall-item col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          <span><%= link_to 'Galería de superobras', '/galeria' %></span>
        </h3>
      </div>
      <div class="panel-body">
        <div class="description">
          <p>Repaso de las mayores adjudicaciones entre <%= year_min() %> y <%= year_max() %>, en los que las obras del AVE son las grandes protagonistas. Desde ampliaciones de hospitales hasta la construcción de túneles y puentes, el mayor de estos grandes contratos supera los 366 millones de euros.</p>
        </div>
        <%= link_to image_tag(image_path(@gallery_picture), :class => 'img-responsive'), '/galeria', :class => 'image' %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_head.html.erb
<head>
  <meta charset="utf-8">

  <!-- Always force latest IE rendering engine or request Chrome Frame -->
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta http-equiv="content-language" content="es-ES" />

  <!-- Use title if it's in the page YAML frontmatter -->
  <% if @title %>
    <title><%= @title %> | Quién Cobra la Obra</title>
  <% else %>
    <title>Quién Cobra la Obra</title>
  <% end %>

  <meta name="description" content="Un mapa de la contratación de obra pública en España">
  <meta name="keywords" content="contrato de servicios, proyecto de obra, constructoras, proyectos de construccion, constructor, obra nueva, obra construccion, proyecto obra, proyecto obra civil, licitación, obra pública, proyecto y construcción de obra, licitaciones públicas, contratación del estado, contratación publica, contrato de obra, contratos publicos, tipos de contratos, obras publicas, licitacion de obra publica, proyecto de construccion civil, proyectos en construccion, proyecto obra civil, concurso obra, contrato publico, contratacion del estado licitaciones, FCC, ACS, sacyr, acciona, ferrovial, villar mir, Florentino Pérez, entrecanales, Koplowitz, Civio, investigación, transparencia, contratos publicos españa, clasificacion de contratista de obra, clasificacion de empresas contratistas de obras, clasificacion contratistas obras, legislación de contratos del sector público, clasificacion contratistas servicios, contratos del sector publico resumen">
  <meta name="author" content="Fundación Ciudadana Civio">

  <% if @title %>
    <meta property="og:title" content="<%= @title %> | Quién Cobra la Obra">
  <% else %>
    <meta property="og:title" content="Quién Cobra la Obra">
  <% end %>
  <meta property="og:description" content="Un mapa de la contratación de obra pública en España">
  <meta property="og:url" content="<%= request.original_url %>">
  <meta property="og:site_name" content="Quién Cobra la Obra">
  <meta property="og:type" content="website">

  <% if @title %>
    <meta name="twitter:title" content="<%= @title %> | Quién Cobra la Obra">
  <% else %>
    <meta name="twitter:title" content="Quién Cobra la Obra">
  <% end %>
  <meta name="twitter:description" content="Un mapa de la contratación de obra pública en España">
  <meta name="twitter:url" content="<%= request.original_url %>">
  <meta name="twitter:creator" content="@civio">

  <!-- Favicons -->
  <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path("apple-touch-icon.png") %>">
  <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path("favicon-32x32.png") %>">
  <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path("favicon-16x16.png") %>">
  <link rel="manifest" href="<%= asset_path("manifest.json") %>">
  <link rel="mask-icon" href="<%= asset_path("safari-pinned-tab.svg") %>" color="#5bbad5">

  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Lato:300,400,700|Merriweather:300,300i,400,400i,700,700i">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

app/views/partials/_header.html.erb
<!-- Civio Navbar -->
<nav id="civio-navbar">
  <div id="civio-navbar-brand-cont">
    <a id="civio-navbar-brand" href="https://civio.es/" title="Civio">
      <svg width="100" height="23" class="icon-civio" viewBox="0 0 200 45" version="1.1" aria-hidden="true"><g fill-rule="evenodd"><path id="p1" d="M188.3 0c5.56 0 10.06 4.42 10.06 9.87 0 5.45-4.5 9.87-10.06 9.87-5.55 0-10.06-4.42-10.06-9.87 0-5.45 4.5-9.87 10.06-9.87z"></path><path id="p2" d="M178.24 34.4c0-5.46 4.5-9.88 10.06-9.88s10.06 4.42 10.06 9.87c0 5.4-4.5 9.83-10.06 9.83-5.55 0-10.06-4.43-10.06-9.87"></path><path d="M58 1.3h12l16.9 41.6h-12z"></path><path d="M104.2 1.3h-12L75.25 42.9h12zM36.46 7C28.12-1.35 14.6-1.35 6.26 7c-8.34 8.33-8.34 21.87 0 30.2 8.33 8.34 21.86 8.34 30.2 0l-7.55-7.55c-4.13 4.17-10.9 4.17-15.1 0s-4.14-10.93 0-15.1 10.97-4.17 15.1 0L36.5 7zM154.6 29.65c-4.17 4.17-10.94 4.17-15.1 0-4.17-4.17-4.17-10.93 0-15.1 4.16-4.17 10.93-4.17 15.1 0 4.16 4.17 4.16 10.93 0 15.1M162.15 7c-8.34-8.34-21.87-8.34-30.2 0-8.35 8.33-8.35 21.87 0 30.2 8.33 8.34 21.86 8.34 30.2 0 8.33-8.33 8.33-21.87 0-30.2M43.2 42.9h10.75V1.3H43.2zm65.04 0H119V1.3h-10.76z"></path></g></svg>
    </a>
  </div>
  <a id="civio-navbar-donate-btn" href="https://civio.es/socios/?source=banner-top" title="Hazte socio">Hazte socio</a>
</nav>

<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '<h1>Quién Cobra la Obra</h1>', '/', :class => 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Artículos', articles_path() %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Todos los contratos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Buscador', awards_path() %></li>
            <li><%= link_to 'Administraciones', public_bodies_path() %></li>
            <li><%= link_to 'Grupos constructores', bidders_path() %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contratopedia <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Guía de la Ley', the_law_path() %></li>
            <li><%= link_to 'Glosario', glossary_path() %></li>
          </ul>
        </li>
        <li><%= link_to 'Metodología', methodology_path() %></li>
      </ul>
      <form class="navbar-form navbar-right" role="search" action="<%=search_path()%>">
        <div class="form-group">
          <input type="text" name="search" class="form-control" placeholder="Busca...">
        </div>
        <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
      </form>

    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/partials/_post.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      <span><%= link_to article.title, article_path(article) %></span>
    </h3>
  </div>
  <div class="panel-body">
    <% if article.photo and !article.photo.url.blank? %>
      <%= link_to image_tag(article.photo.url(:small), :class => 'img-responsive'), article_path(article), :class => 'image' %>
    <% end %>
    <% unless article.lead.blank? %>
    <div class="description">
      <p><%= article.lead.html_safe %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/partials/_post_related_entity.html.erb
<li>
  <%
    path = (entity.class.name == 'Bidder') ? bidder_path(entity) : public_body_path(entity)
  %>
  <div class="picture">
    <%= link_to image_tag('http://lorempixel.com/74/74', :class => 'img-responsive'), path, :class => 'image' %>
  </div>
  <div class="content">
    <%= link_to entity.name, path %>
    <small>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris.</small>
  </div>
</li>

app/views/partials/_posts_comments.html.erb
<div class="post-comments">
  <div id="disqus_thread"></div>
  <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'quincobralaobra'; // required: replace example with your forum shortname

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>

app/views/partials/_sharing_buttons.html.erb
<div class="sharing-buttons">
  <ul class="sharing-buttons-toolbox">
    <li>
      <a class="sharing-button sharing-button-twitter social-twitter" onclick="window.open('https://twitter.com/intent/tweet?url=<%= request.original_url %>&amp;text=<%= title %> - Quién Cobra la Obra - Un proyecto de @Civio','_blank','height=260,width=400')" href="javascript: void(0)" title="Compartir en Twitter">Compartir en Twitter</a>
    </li>
    <li>
      <a class="sharing-button sharing-button-facebook social-facebook" onclick="window.open('https://www.facebook.com/dialog/share?app_id=<%= Rails.configuration.facebook_app_id %>&amp;display=popup&amp;href=<%= request.original_url %>&amp;redirect_uri=<%= request.original_url %>','_blank','height=400,width=400')" href="javascript: void(0)" title="Compartir en Facebook">Compartir en Facebook</a>
    </li>
    <li>
      <a class="sharing-button sharing-button-googleplus social-googleplus" onclick="window.open('https://plus.google.com/share?url=<%= request.original_url %>','_blank','height=400,width=500')" href="javascript: void(0)" title="Compartir en Google+">Compartir en Google+</a>
    </li>
    <li>
      <a class="sharing-button sharing-button-meneame social-meneame" onclick="window.open('http://www.meneame.net/submit.php?url=<%= request.original_url %>','_blank','height=400,width=500')" href="javascript: void(0)" title="Compartir en Menéame">Compartir en Menéame</a>
    </li>
  </ul>
</div>